const $=s=>document.querySelector(s);const api=location.origin;let connections=[],providers=[];const toast=(m)=>{const t=$('#toast');t.textContent=m;t.classList.add('show');setTimeout(()=>t.classList.remove('show'),2800)};const call=async(path,opts={})=>{const r=await fetch(api+path,{headers:{'Content-Type':'application/json',...(opts.headers||{})},...opts});const data=await r.json().catch(()=>({}));if(!r.ok)throw Error(data.detail?.message||data.detail||data.error||`Request failed (${r.status})`);return data};
function view(name){document.querySelectorAll('.view').forEach(x=>x.classList.add('hidden'));$(`#${name}View`).classList.remove('hidden');document.querySelectorAll('.nav').forEach(x=>x.classList.toggle('active',x.dataset.view===name));$('#pageTitle').textContent=name==='query'?'Query studio':name[0].toUpperCase()+name.slice(1)}
document.querySelectorAll('.nav').forEach(b=>b.onclick=()=>view(b.dataset.view));
async function health(){try{const status=await call('/health');$('#healthState').textContent=status.status==='ok'?'Healthy':'Degraded';$('#healthState').style.color=status.status==='ok'?'var(--accent)':'var(--danger)'}catch(e){$('#healthState').textContent='Offline';$('#healthState').style.color='var(--danger)'}}
function fillSelects(){const c=$('#connectionSelect'),p=$('#providerSelect'),selectedConnection=c.value,selectedProvider=p.value;c.innerHTML='<option value="">Default connection</option>'+connections.map(x=>`<option value="${x.connection_id}">${x.name} · ${x.dialect}</option>`).join('');p.innerHTML='<option value="">Default Groq</option>'+providers.map(x=>`<option value="${x.provider_id}">${x.name} · ${x.model}</option>`).join('');c.value=connections.some(x=>x.connection_id===selectedConnection)?selectedConnection:'';p.value=providers.some(x=>x.provider_id===selectedProvider)?selectedProvider:''}
async function loadConnections(){try{const d=await call('/connections');connections=d.connections||[];$('#connectionsList').innerHTML=connections.length?connections.map(x=>`<div class="profile"><div><strong>${x.name}</strong><span>${x.dialect} · ${x.connection_id.slice(0,8)}</span></div><button data-delete-connection="${x.connection_id}">Delete</button></div>`).join(''):'<span class="muted">No connections yet.</span>';fillSelects()}catch(e){toast(e.message)}}
async function loadProviders(){try{const d=await call('/providers');providers=d.providers||[];$('#providersList').innerHTML=providers.length?providers.map(x=>`<div class="profile"><div><strong>${x.name}</strong><span>${x.provider_type} · ${x.model}</span></div><button data-delete-provider="${x.provider_id}">Delete</button></div>`).join(''):'<span class="muted">No providers yet.</span>';fillSelects()}catch(e){toast(e.message)}}
async function loadSchema(){try{const connectionId=$('#connectionSelect').value;const path=connectionId?`/schema?connection_id=${encodeURIComponent(connectionId)}`:'/schema';const d=await call(path);$('#schemaList').innerHTML=(d.chunks||[]).map(x=>`<span class="table-chip">${x.split('\n')[0].replace('Table: ','')}</span>`).join('')||'<span class="muted">No schema loaded.</span>'}catch(e){$('#schemaList').innerHTML=`<span class="muted">${e.message}</span>`}}
async function refreshSchema(){const connectionId=$('#connectionSelect').value;try{if(connectionId){const d=await call(`/connections/${encodeURIComponent(connectionId)}/schema/ingest`,{method:'POST'});toast(d.status==='indexed'?`Indexed ${d.tables} tables in Pinecone`:`Loaded ${d.tables} tables; Pinecone ${d.status}`)}await loadSchema()}catch(e){toast(e.message)}}
$('#runQuery').onclick=async()=>{const question=$('#question').value.trim();if(!question)return toast('Write a question first.');$('#runQuery').disabled=true;$('#traceState').textContent='RUNNING';$('#resultTitle').textContent='Agent is working';$('#resultBody').className='result-body';$('#resultBody').innerHTML='<p class="muted">Retrieving schema, generating SQL, validating, executing...</p>';try{const d=await call('/query',{method:'POST',body:JSON.stringify({question,connection_id:$('#connectionSelect').value||null,provider_id:$('#providerSelect').value||null})});$('#traceState').textContent=d.error?'FAILED':'COMPLETE';$('#resultTitle').textContent=d.error?'Query failed':'Query result';$('#resultBody').innerHTML=`${d.sql?`<pre>${d.sql}</pre>`:''}${d.error?`<p style="color:var(--danger)">${d.error}</p>`:`<div class="rows">${(d.result||[]).map(r=>`<div class="row">${JSON.stringify(r)}</div>`).join('')||'<span class="muted">No rows returned.</span>'}</div>`}<p class="hint">${d.retries||0} correction retries · ${d.provider_id||'default provider'}</p>`;loadHistory()}catch(e){$('#traceState').textContent='FAILED';$('#resultTitle').textContent='Request error';$('#resultBody').innerHTML=`<p style="color:var(--danger)">${e.message}</p>`}finally{$('#runQuery').disabled=false}};
$('#connectionForm').onsubmit=async e=>{e.preventDefault();const f=new FormData(e.target);try{await call('/connections',{method:'POST',body:JSON.stringify(Object.fromEntries(f))});e.target.reset();$('#connectionMessage').textContent='Connection saved and tested.';toast('Connection added');loadConnections()}catch(x){$('#connectionMessage').textContent=x.message;$('#connectionMessage').style.color='var(--danger)'}};
$('#providerForm').onsubmit=async e=>{e.preventDefault();const f=new FormData(e.target);try{await call('/providers',{method:'POST',body:JSON.stringify(Object.fromEntries(f))});e.target.reset();$('#providerMessage').textContent='Provider saved securely.';toast('Provider added');loadProviders()}catch(x){$('#providerMessage').textContent=x.message;$('#providerMessage').style.color='var(--danger)'}};
document.body.onclick=async e=>{const c=e.target.dataset.deleteConnection,p=e.target.dataset.deleteProvider;try{if(c){await call('/connections/'+c,{method:'DELETE'});loadConnections()}if(p){await call('/providers/'+p,{method:'DELETE'});loadProviders()}}catch(x){toast(x.message)}};
async function loadHistory(){try{const d=await call('/history');const rows=d.chats||[];$('#historyList').innerHTML=rows.length?rows.slice().reverse().map(x=>`<div class="history-row"><div><strong>${x.chat_id.slice(0,12)}...</strong><span>${x.connection_id||'Default database'} · ${x.provider_id||'Default Groq'}</span></div><span>${x.response_count} responses</span></div>`).join(''):'<span class="muted">No sessions yet.</span>'}catch(e){toast(e.message)}}
$('#seedDemo').onclick=async()=>{try{const d=await call('/jobs/seed',{method:'POST'});toast(d.queued?'Demo seed queued':'Configure Upstash Redis first')}catch(e){toast(e.message)}};$('#connectionSelect').onchange=loadSchema;$('#healthBtn').onclick=health;$('#refreshConnections').onclick=loadConnections;$('#refreshProviders').onclick=loadProviders;$('#refreshSchema').onclick=refreshSchema;$('#refreshHistory').onclick=loadHistory;health();loadConnections();loadProviders();loadSchema();loadHistory();
